name: cann_openeuler_based

on:
  workflow_dispatch:
  push:
    paths:
      - 'cann/8.1.RC1.alpha001-910b-openeuler22.03-py3.10/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'cann/8.1.RC1.alpha001-910b-openeuler22.03-py3.10/**'
  release:
    types:
      - "published"
    paths:
      - 'cann/8.1.RC1.alpha001-910b-openeuler22.03-py3.10/**'

jobs:
  run-build:
    name: Build and push 8.1.RC1.alpha001-910b-openeuler22.03-py3.10 Image
    uses: ./.github/workflows/main.yml
    with:
        target_name: 8.1.RC1.alpha001-910b-openeuler22.03-py3.10
        context: cann/8.1.RC1.alpha001-910b-openeuler22.03-py3.10
        dockerfile: Dockerfile
        repos: |
          
          docker.io/zhihang161013/cann
          
        common_registry_tags: |
          
          docker.io/zhihang161013/cann:8.1.RC1.alpha001-910b-openeuler22.03-py3.10
          
          docker.io/zhihang161013/cann:openeuler-python3.10-cann8.1.RC1.alpha001
          
          
        event_name: ${{ github.event_name }}
    secrets: inherit
